### PR TITLE
Compatibility with Rails 4.2 and cleanup

### PR DESCRIPTION
**Pull request by pschambacher**
cc @mislav

### CODE REVIEW

**Comment by pschambacher** [comment]
@mislav Feedback?

**Comment by onebree** [comment]
@pschambacher I am assuming that without this PR merged, then the gem does not work on Rails 4.2.0?

**Comment by pschambacher** [comment]
@onebree It is working. That said since the repository doesn't seem maintained we decided to switch to Kaminari.

**Comment by onebree** [comment]
Thanks for the advice. I was looking into that gem as well

**Pull request closed without merging**
