### PR TITLE
Fix some RSpec 3.x incompatibilities.

### PR DESCRIPTION
**Pull request by voxik**

### CODE REVIEW

**Comment by mislav** [comment]
Thanks for the fix, but [we don't use RSpec 3](https://github.com/mislav/will_paginate/blob/67e11dce90a75d98d184e4bcc1120457e58b477b/Gemfile#L8).

**Comment by voxik** [comment]
But you could use RSpec 3.x if you accepted this patch. As far as I can tell, these are the only 2 issues preventing this.

So should I include the updated Gemfile?

**Comment by mislav** [comment]
No, I'm fine using RSpec 2 in this project.

**Comment by voxik** [comment]
Ok, np. Thx for explanation :+1:

**Pull request closed without merging**
