### PR TITLE
Implement fix for Fixnum deprecation

### PR DESCRIPTION
**Pull request by marksiemers**
This also takes care of gem versioning issues with ruby < 2.1

### CODE REVIEW

**Comment by marksiemers** [comment]
@mislav @tisba @007lva - All builds are passing, please let me know if there are any issues with this PR.

**Comment by silverdr** [comment]
I personally don't like the "dynamic" `0.class` approach. It's like saying "I don't know what it is so let it be whatever it is". What if at some hypothetical point Ruby will start returning `0.class => Zero` for example? Rails guys did it with `Integer` constant. Explicit and probably faster too.

**Comment by marksiemers** [comment]
I can look into switching it.
For the Rails example, is the code you are referring to?
https://github.com/rails/rails/blob/17ef58db1776a795c9f9e31a1634db7bcdc3ecdf/activesupport/lib/active_support/xml_mini.rb#L51

**Comment by tisba** [comment]
To be compatible across Ruby versions, AFAIK, doing the `0.class` thing is the best way to do it. Happy to learn a better way though :)

**Comment by silverdr** [comment]
@marksiemers: Actually I was referring to the "[Support for unified Integer class in Ruby 2.4+ #25056](https://github.com/rails/rails/pull/25056)" Rails PR. 
@tisba: we discussed this on the other PR - there is no need for dynamic `0.class` unless you know of a reasonable Ruby version in which `Fixnum` and `Bignum` does not inherit from Integer.

**Comment by marksiemers** [comment]
It seems to me there is a tradeoff for trying to future proof this:
`if Integer == Fixnum`
The `Fixnum` constant is deprecated, meaning this code must change in the future. Although it will error loudly when that time comes.

The `0.class` approach, the `#class` method is not deprecated and likely won't be, and the likelihood of ruby switching to a `NegativeInteger`, `ZeroInteger`, `PositiveInteger` (or something similar) is not out of the question, but it is less than a 100% chance - which is where we stand with `Fixnum` being deprecated.

Although, the `0.class` approach will error silently or unexpectedly if something does cause it to break.

**Comment by silverdr** [comment]
True. There is no question about the need for switching out from Fixnum. Even if currently only for the sake of having clean output when testing :-) And thanks a lot for doing the much harder part of the job and taking the PR farther than I did with mine. I didn't get into fixing the CI part for older versions so yours is now the primary candidate for being merged and that's great. As for the `if Integer == Fixnum` - it raised questions also on the Rails PR. But here we don't need this kind of conditionals, do we? Also we don't expect `#class` method to be deprecated but as I wrote at the beginning - using the `0.class` is like saying "well, I don't know what to expect here so I'll use more resources and make it not fail - hopefully for some time" ;-) But we know what to expect here, don' t we?

**Comment by marksiemers** [comment]
@silverdr - I see your point - dynamic classes are certianly not as solid as static class checking. In ruby, so much is dynamic anyway though, if you think of it in a duck-typing sense, maybe it makes more sense.

I don't care exactly what class this is, just as long is it responds to methods the same way that `0` does, then we're good.

Similar to using `CSV::Row` as a hash...as long at `#fetch` and `#[]` who cares if it is a hash or a `CSV::Row`

**Comment by dsandstrom** [comment]
Alternatively, you could switch the logic around and do:

```ruby
item.is_a?(Symbol) ? send(item) : page_number(item)
```

If item is not a number, it's `:previous`, `:next`, or `:gap`, right?  The downside is this would break if strings are ever used instead of symbols.

**Comment by silverdr** [comment]
@marksiemers: You are absolutely right that duck-typing and related behaviour has its firm place in the Ruby world. What I am saying in this thread though is:

- `will_paginate` used ::Fixnum constants for years
- Ruby deprecates using specific classes in favour of the Integer superclass
- I see neither benefits of nor a need to change the static behaviour used in the previous versions of `will_paginate` into a potentially more resource hungry dynamic behaviour

Therefore if there is no clear benefit of changing it, then IMHO the old, "static" approach fits better here. My $0.02. Choice is of course yours (and mislav's).

**Comment by marksiemers** [comment]
After looking at the acrogenesis/will_paginate-foundation PR referenced above, I think doing this in a better way is possible - using more reliable static class checking.

The non-spec code can safely check `is_a?(Integer)` since `Fixnum` inherits. One of the specs is checking `instance_of?` so that needs `Fixnum` or `Integer` directly. 

@silverdr - This did end up looking a lot like your code.

**Comment by silverdr** [comment]
@marksiemers: great, thanks. :-) Now we only need to get your code merged!

**Comment by mislav** [comment]
@marksiemers Thanks for your contribution and the discussion! I've went and merged some earlier PRs that fix the Fixnum problem and the test failures in CI, but basically they were similar to your fixes.

**Pull request closed without merging**
