### PR TITLE
Fix deprecation warnings for Ruby 2.4

### PR DESCRIPTION
**Pull request by asurin**
Fixes deprecation warnings, as they're making my spec output hard to read

### CODE REVIEW

**Comment by tisba** [comment]
@asurin the best practice seem to check for `0.class` instead of `Integer` directly. This ensures compatibility with older rubies.

**Comment by asurin** [comment]
@tisba @mislav Brought in line with best practices.  Any chance of a merge and release?

**Comment by tisba** [comment]
This looks good to me! The travis build broke because of

```
public_suffix requires Ruby version >= 2.0
```

which does not seem to be caused by these changes.

**Comment by asurin** [comment]
@mislav any chance of a merge?

**Comment by marksiemers** [comment]
This PR fixes the build errors: https://github.com/mislav/will_paginate/pull/538

**Comment by mislav** [comment]
Thanks for the contribution! I merged an earlier PR which contained basically a similar fix. The new release is now compatible with Ruby 2.4.

**Pull request closed without merging**
