### PR TITLE
passing scope to url_for

### PR DESCRIPTION
**Pull request by terralab**
this is a fix to allow for scope to be passed in to url_for, this is necessary for mountable engine support in rails 3.1. let me know if you have any questions
thanks,
adam

### CODE REVIEW

**Comment by atomgiant** [comment]
@mislav - I too am hitting this due to engine namespaces.  I was able to work around it by adding a custom link renderer and overriding the url method to add support for a custom :url_builder option like so:

```ruby
    def url(page)
      @base_url_params ||= begin
                             url_params = merge_get_params(default_url_params)
                             merge_optional_params(url_params)
                           end

      url_params = @base_url_params.dup
      add_current_page_param(url_params, page)

      # Add optional url_builder support
      if @options[:url_builder]
        @options[:url_builder].call(url_params)
      else
        @template.url_for(url_params)
      end
    end
```

You can then specify a custom url builder via the will_paginate options like so:

```ruby
    <%=
      will_paginate items, {
        url_builder: -> (params) { myengine.url_for(params) },
        renderer: CustomPaginationHelper::LinkRenderer,
        inner_window: 2
      }
    %>
```

This should allow customization for any edge-case url construction as well.  If you'd like me to submit a pull request for this let me know.

**Comment by dancinglightning** [comment]
This did the trick for me. I use will_paginate-bootstrap and am patching the renderer there to call my engine instead of @template. Not pretty, but works. 

I don't know why i need to though, as it worked in 4.1 but stopped in 4.2. My engine is not isolated and maybe that does it (or i messed up)

Whatever happened to this request, it looked like it was going to make it but then didn't ?

**Comment by mislav** [comment]
> Whatever happened to this request, it looked like it was going to make it but then didn't ?

Yes I asked for an amended version of this PR, but never got it.

**Comment by dancinglightning** [comment]
Hi @mislav , maybe that is because one doesn't need that anymore.
It worked for me in 4.1 and in 4.2 i had to add a helper into my base engine controller like

    class OfficeController < ApplicationController
       helper  OfficeClerk::Engine.routes.url_helpers
       include OfficeClerk::Engine.routes.url_helpers

The include makes the urls available in the code, but the helper is needed to get it into the views.
With that all scoping is unneccessary.
I think in isolated engines this is taken care off.
So all is good, maybe some documentation, but this pr is not needed i think

**Comment by sintro** [comment]
@dancinglightning, this didn`t work for me.
In my case, the controller which renders the page having will_paginate belongs to engine, but the route is defined in main_app. Of course, will_paginate tries to get url by current engine`s scope, and fails. So I tried to use your advice, but included the main_app:
```
   helper  Rails.application.routes.url_helpers
   include Rails.application.routes.url_helpers
```
This didn`t work. Temporarily solved my problem by defining route in engine`s class (right in my common application`s routes.rb:
```
Refinery::Core::Engine.routes.draw do
  namespace :blog, :path => Refinery::Blog.page_url do
    get 'search', to: 'posts#search', as: 'search'
  end
end
```
)
This seems to me more organic way to solve the problem, but it is ugly too, because this is class opening using and there is a lack of route ordering control.

**Comment by the-teacher** [comment]
@sintro not sure, but, I think, kaminari  has the same problem.

**Comment by JohnMerlino1** [comment]
Nothing above has worked for me at all. I am using a Rails 4 app with Fullcalendar::Engine.
I have the following in my routes.rb file:

[  mount FullcalendarEngine::Engine , at: "/fullcalendar_engine"

  resources :events,  module: 'fullcalendar_engine' , only: [:index, :show] do

    collection do
      get 'calendar', to: 'events#calendar', as: 'calendar'
      post :check
    end
  end](url)

I tried this:

[%= will_paginate @events, {
            renderer: CustomLinkRenderer,
            url_builder: -> (params) { FullcalendarEngine::Engine.routes.url_for(params) },
            params: { controller: 'events', action: :index, document_type: 'Contact', document_id: params[:id] }
        }
](url)

I created the CustomLinkRenderer in /lib:
[
class CustomLinkRenderer < WillPaginate::ActionView::LinkRenderer
  def url(page)
    @base_url_params ||= begin
      url_params = merge_get_params(default_url_params)
      url_params[:only_path] = true
      merge_optional_params(url_params)
    end

    url_params = @base_url_params.dup
    add_current_page_param(url_params, page)

    if @options[:url_builder]
      @options[:url_builder].call(url_params)
    else
      @template.url_for(url_params)
    end
  end
end](url)

And I still get the following error:

[No route matches {:action=>"index", :contactable_type=>"Lead", :controller=>"events", :document_id=>"5760535f4d6163133e020000", :document_type=>"Contact", :id=>"5760535f4d6163133e020000", :page=>2}](url)

Can anyone offer me any kind of solution that will work?

**Comment by mislav** [comment]
Hi all, thank you for the discussion so far and for proposed fixes, and sorry for the long period of inactivity on my end.

I'm going to close this as it was something that I never felt strongly about adding to the library. For people who need to customize where or how `@template.url_for` is called when rendering pagination links, you might want to subclass and tweak the link renderer.

**Pull request closed without merging**
