### PR TITLE
Allow customizing pagination classes

### PR DESCRIPTION
**Pull request by DylanJ**

### CODE REVIEW

**Comment by sungwoncho** [comment]
Why is this needed? In the same vein, perhaps you could allow custom pagination ids.

**Comment by jeremywadsack** [comment]
I could see that being useful for simpler [Bootstrap integration](https://gist.github.com/isaacbowen/1182136).

**Comment by mislav** [comment]
Thanks for the contribution, but I don't want to add more options to customize the pagination than there already are. See https://github.com/mislav/will_paginate/wiki/Link-renderer for information how to customize every aspect of pagination via subclassing the LinkRenderer in Ruby.

**Comment by hidroo** [comment]
Hello,

I did this, could you please confirm if this is the right path:

```
class UnifyThemePagination < WillPaginate::ViewHelpers::LinkRenderer

  protected
  def page_number(page)
    ...
  end
  
  def gap
    ...
  end

  def previous_or_next_page(page, text, classname)
    ...
  end
      
  def html_container(html)
    ...
  end

  # These are copied from action_view and are needed in order to generate the url.
  # It is defined there as class LinkRenderer < ViewHelpers::LinkRenderer which is kind of a monkey patch. I will ask
  # the developer about it.

  GET_PARAMS_BLACKLIST = [:script_name, :original_script_name]

  def default_url_params
    {}
  end

  def url(page)
    @base_url_params ||= begin
      url_params = merge_get_params(default_url_params)
      url_params[:only_path] = true
      merge_optional_params(url_params)
    end

    url_params = @base_url_params.dup
    add_current_page_param(url_params, page)

    @template.url_for(url_params)
  end

  def merge_get_params(url_params)
    if @template.respond_to? :request and @template.request and @template.request.get?
      symbolized_update(url_params, @template.params, GET_PARAMS_BLACKLIST)
    end
    url_params
  end

  def merge_optional_params(url_params)
    symbolized_update(url_params, @options[:params]) if @options[:params]
    url_params
  end

  def add_current_page_param(url_params, page)
    unless param_name.index(/[^\w-]/)
      url_params[param_name.to_sym] = page
    else
      page_param = parse_query_parameters("#{param_name}=#{page}")
      symbolized_update(url_params, page_param)
    end
  end

  private

  def parse_query_parameters(params)
    Rack::Utils.parse_nested_query(params)
  end
end
```

And then rendering using:

```

<%= will_paginate @materials, { renderer: UnifyThemePagination } %>

```

**Pull request closed without merging**
