### PR TITLE
Add #pagination_link_tags helper method

### PR DESCRIPTION
**Pull request by lloydmeta**
This adds a #rel_next_prev_link_tags method to will_paginate. Essentially
taken straight from [Kaminari's implementation](https://github.com/amatsuda/kaminari/pull/200/files)

```
#In head:
<head>
  <title>My Website</title>
  <%= yield :head %>
</head>

#Somewhere in body:
<% content_for :head do %>
  <%= pagination_link_tags @items %>
<% end %>
```

### CODE REVIEW

**Comment by Abundnce10** [comment]
@mislav has this feature been added yet?

**Comment by lloydmeta** [comment]
Since I keep getting notifications for people wanting it merged or bumping the related #183 issue, I assume that (some) people do want this feature in

This PR is now a bit over a year and a half years old, and I haven't touched Ruby for about that long, so I'm getting more and more rusty. In fact, Ruby (bundler, or RVM, or ...) doesn't even work properly on my current home computer. It took me a while to figure out why the Travis builds were failing (that Rails 3.2 w/ 2.1.2 is a WTF for sure).

I've solved the merge conflicts in hopes that this will help speed things along before this PR reaches legal drinking age ;) Good luck !

As of writing, this merges and passes all tests (plus a I threw in a bonus: `sudo: false` in `.travis.yml` means faster CI.

**Comment by nickboyce** [comment]
@lloydmeta I was hoping @mislav would merge this into a release, but otherwise we intend on taking your code and monkey-patching it into our config. Thanks!

**Comment by xevix** [comment]
:+1:

**Comment by mpolakis** [comment]
hi @mislav and @lloydmeta thanks for your work on the gem and this particular PR. What is the current status though? I happen to need this. Thanks.

**Comment by mislav** [comment]
Sorry for not acting on this sooner, but I wasn't maintaining this project for a while, and I've declared it feature-frozen today. Features like these should be implemented individually in one's application.

@lloydmeta Thank you for your contribution!

**Pull request closed without merging**
